#!/bin/bash
sudo apt-get install golang
sudo apt install libasound2-dev
go get github.com/pkg/errors
go get github.com/hajimehoshi/oto
go get github.com/hajimehoshi/go-mp3
go get -u github.com/faiface/beep
go get github.com/nsf/termbox-go
