#!/bin/bash
nfilesinicial=$(ls /Volumes/Alarms|wc -l)
echo n files is $nfilesinicial
while true; do
   nfiles=$(ls /Volumes/Alarms|wc -l)
   if [ $nfiles -ne $nfilesinicial ]; then
      echo Alarm!
      afplay ~/Desktop/CBNF6LK-security-breach-alarm.mp3
      nfilesinicial=$nfiles
   fi
   sleep 1
done